vehicles: fix serialization regression  in  FileCorruptedCacheException
Motivation:
Commit dea4beb have converted usage of guava's Optional to jdk native Optional.
However, jdk Optional is not implementing serializable interface and, as
a result, NotSerializableException is thrown when FileCorruptedCacheException
is sent from one cell to an other:

dmg.cells.nucleus.SerializationException: Failed to serialize object because the object is not serializable (this is usually a bug)
        at dmg.cells.nucleus.CellMessage.encode(CellMessage.java:211) ~[cells-4.2.7.jar:4.2.7]
        at dmg.cells.nucleus.CellMessage.encode(CellMessage.java:187) ~[cells-4.2.7.jar:4.2.7]
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:466) ~[cells-4.2.7.jar:4.2.7]
        at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:408) ~[cells-4.2.7.jar:4.2.7]
        at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:445) ~[cells-4.2.7.jar:4.2.7]
        at dmg.cells.nucleus.AbstractCellComponent.sendMessage(AbstractCellComponent.java:41) ~[cells-4.2.7.jar:4.2.7]
        at diskCacheV111.namespace.PnfsManagerV3.postProcessMessage(PnfsManagerV3.java:1754) ~[dcache-core-4.2.7.jar:4.2.7]
        at diskCacheV111.namespace.PnfsManagerV3.processPnfsMessage(PnfsManagerV3.java:1698) ~[dcache-core-4.2.7.jar:4.2.7]
        at diskCacheV111.namespace.PnfsManagerV3$ProcessThread.run(PnfsManagerV3.java:1591) ~[dcache-core-4.2.7.jar:4.2.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: java.io.NotSerializableException: java.util.Optional
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_161]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_161]
        at dmg.cells.nucleus.CellMessage.encode(CellMessage.java:206) ~[cells-4.2.7.jar:4.2.7]
        ... 11 common frames omitted

Modification:
Update FileCorruptedCacheException to store value fields, possible nulls and
convert them to Optional only in getters.

Result:
No NotSerializableException.

NOTICE: this change breaks compatibility with existing code. However, as
messages can't be serialized anyway we break already broken compatibility.

Acked-by: Albert Rossi
Target: master, 4.2, 4.1, 4.0
Require-book: no
Require-notes: yes